// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLADILrnGjak0ey9Pw7vlNmfE2eTWdSKs',
    appId: '1:678896429784:web:a6d9511e950217783c85ad',
    messagingSenderId: '678896429784',
    projectId: 'healthy-meal-app-65d6a',
    authDomain: 'healthy-meal-app-65d6a.firebaseapp.com',
    storageBucket: 'healthy-meal-app-65d6a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9qLR1p1OcM2NMHDCG9tkuGY4vJBc9-Jw',
    appId: '1:678896429784:android:58a1bfa0e3980aa23c85ad',
    messagingSenderId: '678896429784',
    projectId: 'healthy-meal-app-65d6a',
    storageBucket: 'healthy-meal-app-65d6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf_oVtmh6FLN3SVNoCfBFGfRV0J9apnBg',
    appId: '1:678896429784:ios:c43331e5a10a61983c85ad',
    messagingSenderId: '678896429784',
    projectId: 'healthy-meal-app-65d6a',
    storageBucket: 'healthy-meal-app-65d6a.firebasestorage.app',
    iosBundleId: 'com.example.healthyFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf_oVtmh6FLN3SVNoCfBFGfRV0J9apnBg',
    appId: '1:678896429784:ios:c43331e5a10a61983c85ad',
    messagingSenderId: '678896429784',
    projectId: 'healthy-meal-app-65d6a',
    storageBucket: 'healthy-meal-app-65d6a.firebasestorage.app',
    iosBundleId: 'com.example.healthyFoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLADILrnGjak0ey9Pw7vlNmfE2eTWdSKs',
    appId: '1:678896429784:web:c512d659c061a5d43c85ad',
    messagingSenderId: '678896429784',
    projectId: 'healthy-meal-app-65d6a',
    authDomain: 'healthy-meal-app-65d6a.firebaseapp.com',
    storageBucket: 'healthy-meal-app-65d6a.firebasestorage.app',
  );
}
